Glossary
mozilla/data-docs pull request #566
Opened 2020-10-09 02:28 UTC by elkevorh

Glossary - added terms and definitions

2020-10-09 19:54 UTC, wlach requested changes
Hi Elke, a bunch of suggestions but mostly looks good! Tell me what you think and I can merge it next week.

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +<!-- TOC -->
```suggestion
<!-- toc -->
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
This should be automatically generated by the table of contents:

```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +<!-- /TOC -->
```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +The id property of the Firefox browser returns the universally unique identifier of the Client object.
```suggestion
A unique id identifying the client who sent a [ping](#ping).
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +Data scientists at Mozilla are a team with a broad array of technical backgrounds and a core set of common professional skills: 1) applying statistical methods to noisy data to answer questions about
We should probably double check this definition with data science, but meanwhile we can improve the formatting a bit:

```suggestion
Data scientists at Mozilla are a team with a broad array of technical backgrounds and a core set of common professional skills: 

* applying statistical methods to noisy data to answer questions about what, how, or why something is happening
* transform unstructured data into usable metrics and models
* augmenting strategic product and decision-making with empirical evidence created and curated by the team.
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## dataset
```suggestion
## Dataset
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +A set of data, which includes ping data, derived datasets, etc.; sometimes it is used synonymously with “table”; sometimes it is used technically to refer to a [BigQuery](https://cloud.google.com/big
We should probably add a definition for table as well, now that I look at it.

```suggestion
A set of data, which includes ping data, derived datasets, etc.; sometimes it is used synonymously with “table”; sometimes it is used technically to refer to a [BigQuery](#bigquery) dataset, which represents a container for one or more tables.
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
Seems to be a less refined version of the definition below, guessing this got included by mistake.

```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## derived dataset
```suggestion
## Derived Dataset
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +A processed dataset, such as the clients_daily dataset. This is in contrast to a raw dataset, which is typically a collection of pings. This data can be computed from some lower-level data, but is st
```suggestion
A processed dataset, such as [Clients Daily](..datasets/batch_view/clients_daily/reference.md). At Mozilla, this is in contrast to a raw ping table which represents (more or less) the raw data submitted by our users.
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
Let's skip these non-data topics. We can refer people to the wiki for more information on them.

```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +Glean is Mozilla’s product analytics & telemetry solution that provides a consistent experience and behavior across all of our products. Most of Mozilla's mobile apps, including Fenix, have been adap
```suggestion
Glean is Mozilla’s product analytics & telemetry solution that provides a consistent experience and behavior across all of our products. Most of Mozilla's mobile apps, including Fenix, have been adapted to use the Glean SDK. For more information, see the [Glean Overview](./glean/glean.html).
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## ingestion
```suggestion
## Ingestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## metric
```suggestion
## Metric
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
Let's skip this for now.

```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## ping
```suggestion
## Ping
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## ping table
```suggestion
## Ping Table
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +A set of pings that is stored in BigQuery as a table.
```suggestion
A set of pings that is stored in a BigQuery table. See article on [raw ping datasets](../datasets/pings.md).
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## pipeline
```suggestion
## Pipeline
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
Let's skip the code  reference

```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +The bulk of the data that is handled by this pipeline is Firefox Telemetry data. The same tool-chain is used to collect, store, and analyze data that comes from many sources.
```suggestion
The bulk of the data that is handled by this pipeline is Firefox Telemetry data. The same tool-chain is used to collect, store, and analyze data that comes from many sources.
For more information, see [An overview of Mozilla’s Data Pipeline](./pipeline/gcp_data_pipeline.html).
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## probe
```suggestion
## Probe
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## profile
```suggestion
## Profile
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +All of the changes a user makes in Firefox, like the home page, what toolbars you use, installed addons, saved passwords and your bookmarks, are all stored in a special folder, called a profile. Tele
```suggestion
All of the changes a user makes in Firefox, like the home page, what toolbars you use, installed addons, saved passwords and your bookmarks, are all stored in a special folder, called a profile. Telemetry stores archived and pending pings in the profile directory as well as metadata like the [client id](#client-id). See also [Profile Creation](./profile/profile_creation.html)
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## retention
```suggestion
## Retention
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## query
```suggestion
## Query
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +TBD
Let's take a stab at defining this.

```suggestion
Typically refers to a query written in the SQL syntax, run on (for example) [STMO](#stmo).
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
Either duplicates or overly specific for a terminology section.

```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +A schema is the organization or structure for a database. The activity of data modeling leads to a schema. Mozilla’s source schema is available on the [mozilla-services/socorro GitHub repository](htt
I think this isn't quite right. Here's another stab at the concept

```suggestion
A schema is the organization or structure for our data. We use schemas at many levels (in data ingestion and storage) to make sure the data we submit is valid and possible to be processed efficiently.
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## session
```suggestion
## Session
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +The period of time that it takes between Firefox being started until it is shut down.
```suggestion
The period of time that it takes between Firefox being started until it is shut down. See also [subsession](#subsession).
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +* **Subsession**: `Sessions` are split into `subsessions` after every 24-hour time period has passed or the environment has changed.
```suggestion
## Subsession

In Firefox, [Sessions](#sessions) are split into subsessions after every 24-hour time period has passed or the environment has changed.
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
Let's skip this one, it's hard to explain and not necessary for most people to know.

```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
Let's skip this for now.

```suggestion
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +## sql.telemetry.mozilla.org
```suggestion
## STMO (sql.telemetry.mozilla.org)
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +A service for creating queries and dashboards. See [STMO under analysis tools](https://docs.telemetry.mozilla.org/tools/interfaces.html#sqltelemetrymozillaorg-stmo).
```suggestion
A service for creating queries and dashboards. See [STMO under analysis tools](../tools/interfaces.html#sqltelemetrymozillaorg-stmo).
```

2020-10-09 19:54 UTC, wlach commented on src/concepts/terminology.md
> +
```suggestion
```

2020-10-15 22:11 UTC, willkg commented
@wlach ^^^ That rebases against master tip and addresses all your comments.

2020-10-15 22:16 UTC, willkg commented
@wlach: Some of these are spelling errors, but others aren't. How do you deal with the non-errors?

```
$ scripts/spell_check.sh
    src/concepts/terminology.md
       10 | ## AET 
       12 | Ecosystem Telemetry; see the [PRD](https://docs.google.com/docu 
       34 | ## Data Practioner 
       68 | IP Geolocation involves attempting to discov 
       76 |  users use the product? Among profilesactive at least once in the week end 
>> 5 spelling errors found in 155 files
```

2020-10-16 21:26 UTC, wlach commented
> @wlach: Some of these are spelling errors, but others aren't. How do you deal with the non-errors?

Sorry for the late response! GitHub needs needinfo, apparently.

You can add new spellings to `.spelling`. See: https://github.com/mozilla/data-docs#spell-checking

2020-10-16 22:24 UTC, willkg commented
@wlach Thank you for that! This is ready for another review.

2020-10-19 13:57 UTC, wlach approved these changes
This looks good, there are a few things we should probably also do (e.g. link out to https://wiki.mozilla.org/Acronyms) but that can be done in another PR

2020-10-19 13:57 UTC, merged