Updated analytics diagram with word logos
mozilla/data-docs pull request #691
Opened 2022-01-27 20:28 UTC by ANich

2022-01-27 23:41 UTC, sean-rose requested changes
Those changes are definitely helpful, thanks!

For Colab, how about using a logo that says "Colab" rather than just "Co"? ([example](https://miro.medium.com/max/1400/1*Lad06lrjlU9UZgSTHUoyfA.png))

2022-01-28 17:28 UTC, sean-rose approved these changes

2022-01-28 18:22 UTC, sean-rose commented
btw, with how you're generating the diagram, if PNG is an option I think that might be a better format for this than JPEG.

2022-01-31 15:27 UTC, ANich commented
> btw, with how you're generating the diagram, if PNG is an option I think that might be a better format for this than JPEG.

Seems like that's an existing [feature request](https://community.miro.com/wish-list-32/export-transparent-png-s-1865) for Miro. Currently supports JPG and a Vector PDF

2022-01-31 15:28 UTC, merged