Update reference.md
mozilla/data-docs pull request #739
Opened 2022-09-29 20:12 UTC by pissac17

update client ltv table names to mozdata.revenue.client_ltv

2022-09-29 20:44 UTC, badboy requested changes
Minimal formatting issue, but then we should land this.

2022-09-29 20:44 UTC, badboy commented on src/datasets/search/client_ltv/reference.md
> + `moz-fx-data-shared-prod`.revenue.client_ltv
```suggestion
  `moz-fx-data-shared-prod`.revenue.client_ltv
```

2022-10-03 14:15 UTC, pissac17 reviewed
formatting changes as requested by @badboy

2022-10-04 21:29 UTC, alekhyamoz approved these changes
ltgm

2022-10-04 21:57 UTC, merged

2022-10-05 10:34 UTC, akkomar commented on src/datasets/search/client_ltv/reference.md
> +  `moz-fx-data-shared-prod`.revenue.client_ltv
This is fine but generally we should use views in `mozdata` instead of `moz-fx-data-shared-prod` in user-facing documentation.