[ADPRODUCTS-370] Documentation updates with CS data revamp
mozilla/data-docs pull request #741
Opened 2022-10-13 19:06 UTC by skahmann3

2022-10-13 19:09 UTC, skahmann3 commented
@rebecca-burwei - created documentation for Tiles, noting the new datasetes. Please review when you get a chance! Though I'll hold off on merging until we know where the new tables are landing in Looker

2022-10-13 20:05 UTC, rebecca-burwei reviewed
Some minor changes, but overall looks good.

2022-10-13 20:05 UTC, rebecca-burwei commented on src/datasets/other/sponsored tiles/sponsored_tiles.md
> +Firefox Sponsored Tiles is an advertising-based feature available on the new tab of both desktop and mobile Firefox browsers. This feature populates the new tab's Top Sites section with up to two Spo
```suggestion
Firefox Sponsored Tiles is an advertising-based feature available on the new tab of both desktop and mobile Firefox browsers. This feature populates the new tab's Top Sites section with up to two Sponsored Tiles. These Sponsored Tiles display a company logo and link to the company website. Mozilla's Contile serves the advertisements and may refresh the advertisers every 15 minutes. Each click on a Sponsored Tile generates revenue for Mozilla.
```

2022-10-13 20:05 UTC, rebecca-burwei commented on src/datasets/other/sponsored tiles/sponsored_tiles.md
> +| All Mozillians               | `telemetry.sponsored_tiles_clients_daily`     | TBD                                    | Workhorse dataset for Sponsored Tiles, includes desktop and mobile data. All
```suggestion
| All Mozillians               | `telemetry.sponsored_tiles_clients_daily`     | TBD                                    | Workhorse dataset for Sponsored Tiles, includes desktop and mobile data. All new Sponsored Tiles metrics are added to this table. Does not include advertiser data. |
```

2022-10-13 20:05 UTC, rebecca-burwei commented on src/datasets/other/sponsored tiles/sponsored_tiles.md
> +| Revenue | `contextual_services.event_aggregates` x  `revenue.revenue_data`   | Revenue > AdM Revenue with Telemetry  | Revenue information combined with usage metrics. This dataset is useful for CP
I think this dataset limited to people in both Revenue and Contextual Services.

2022-10-14 20:37 UTC, rebecca-burwei approved these changes

2022-10-17 14:00 UTC, badboy requested changes
Please use an underscore `_` instead of spaces in directory and file names.
Additionally this file is not referenced anywhere, and thus won't be accessible in the book.
You can add it to the table of contents in the `SUMMARY.md` file.

I think addressing these 2 things should then make the tests pass as well.

2022-10-17 18:42 UTC, skahmann3 commented
Thanks for catching those edits, @badboy. Will you re-review? But please don't merge changes yet, we're waiting for another BQ table to land before finalizing these updates

2022-10-18 08:51 UTC, badboy approved these changes
No blocker from my side then. Merge when you are ready.

2022-11-10 18:31 UTC, rebecca-burwei approved these changes
Looks good!

2022-11-11 01:28 UTC, merged