DENG-432. Due documentation for the active_users_aggregates_* tables
mozilla/data-docs pull request #743
Opened 2022-10-27 15:59 UTC by lucia-vargas-a

This PR adds the documentation of the active_users_aggregates tables that we use build many core metrics and expose them in Looker.

It also aims to add a good practices to query views instead of tables.

2022-10-31 15:52 UTC, gkabbz approved these changes

2022-11-01 13:39 UTC, badboy requested changes
prettier is a bit more picky about these things.
I added suggestions for everything it complained about so you can apply that in the web UI.

2022-11-01 13:39 UTC, badboy commented on src/datasets/bigquery/active_users_aggregates/reference.md
> +| active_users_aggregates_attribution | Table `telemetry.active_users_aggregates_attribution` | [Explore](https://mozilla.cloud.looker.com/explore/combined_browser_metrics/active_users_aggregates_att
```suggestion
| `active_users_aggregates`             | Table `telemetry.active_users_aggregates`             | [Explore](https://mozilla.cloud.looker.com/explore/combined_browser_metrics/active_users_aggregates)             |
| `active_users_aggregates_device`      | Table `telemetry.active_users_aggregates_device`      | [Explore](https://mozilla.cloud.looker.com/explore/combined_browser_metrics/active_users_aggregates_device)      |
| `active_users_aggregates_attribution` | Table `telemetry.active_users_aggregates_attribution` | [Explore](https://mozilla.cloud.looker.com/explore/combined_browser_metrics/active_users_aggregates_attribution) |
```

2022-11-01 13:39 UTC, badboy commented on src/datasets/bigquery/active_users_aggregates/reference.md
> +#### Active users aggregates for attribution
```suggestion
#### Active users aggregates for attribution

```

2022-11-01 13:39 UTC, badboy commented on src/datasets/bigquery/active_users_aggregates/reference.md
> +#### Active users aggregates for device
```suggestion
#### Active users aggregates for device

```

2022-11-01 13:39 UTC, badboy commented on src/datasets/bigquery/active_users_aggregates/reference.md
> +#### Active users aggregates
```suggestion
#### Active users aggregates

```

2022-11-01 13:39 UTC, badboy commented on src/datasets/bigquery/active_users_aggregates/reference.md
> +less regularity  than other dimensions and mostly for specific purposes.
```suggestion
less regularity than other dimensions and mostly for specific purposes.
```

2022-11-01 13:39 UTC, badboy commented on src/datasets/bigquery/active_users_aggregates/reference.md
> +## Looker visualizations with period over period analysis
```suggestion
## Looker visualizations with period over period analysis

```

2022-11-14 11:25 UTC, lucia-vargas-a commented on src/datasets/bigquery/active_users_aggregates/reference.md
> +|-------------------------------------|-------------------------------------------------------|--------------------------------------------------------------------------------------------------------
Oh wow, this one

2022-11-14 11:30 UTC, lucia-vargas-a reviewed
@badboy Thanks a lot for the review & suggestions!

2022-11-14 13:03 UTC, badboy approved these changes

2022-11-14 13:04 UTC, merged