Pi mobile dataset
mozilla/data-docs pull request #813
Opened 2024-01-30 15:31 UTC by pissac17

data documentation for Mobile search tables regarding updated normalized app name

2024-01-30 18:34 UTC, pissac17 commented
documentation for Mobile search tables regarding updated normalized app name

2024-01-31 11:00 UTC, badboy commented
you will have to add it to `SUMMARY.md` so that it shows up in the rendered book

2024-01-31 11:03 UTC, badboy commented on src/datasets/search/mobile_search_clients_sources_daily/intro.md
> +-->
Hm, I see this commented out part seems to be in several other pages as well. 
IMO we should just remove it here though.

```suggestion
```

2024-01-31 18:42 UTC, skahmann3 approved these changes
LGTM

2024-02-01 10:32 UTC, badboy requested changes
as said: you will have to add it to `SUMMARY.md` so that it shows up in the rendered book.

2024-02-12 14:14 UTC, badboy approved these changes

2024-02-12 14:15 UTC, merged